name: Update README ⭐
on:
  push:
    branches: 
      - 'master'
    
jobs:
  results-table:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: aoc-stars 2022
        uses: k2bd/advent-readme-stars@v1
        with:
          userId: ${{ secrets.AOC_USERID }}
          year: 2021
          sessionCookie: ${{ secrets.AOC_SESSION }}
          tableMarker: <!--- advent_readme_stars table_2021 --->
      - name: aoc-stars 2021
        uses: k2bd/advent-readme-stars@v1
        with:
          userId: ${{ secrets.AOC_USERID }}
          year: 2022
          sessionCookie: ${{ secrets.AOC_SESSION }}
          tableMarker: <!--- advent_readme_stars table_2022 --->
      - name: aoc-badges
        uses: joblo2213/aoc-badges-action@v3
        with:
          userid: ${{ secrets.AOC_USERID }}
          session: ${{ secrets.AOC_SESSION }}
          year: 2021
          file: 'README.md'

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README stats
          file_pattern: README.md