name: Update README ⭐
on:
  push:
    branches: 
      - 'master'
    
jobs:
  results-table:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: advent-readme-stars
        uses: k2bd/advent-readme-stars@v1
        with:
          userId: Averbea
          leaderboardId: 1717853
          year: 2021
          sessionCookie: ${{ secrets.AOC_SESSION }}
          tableMarker: <!--- advent_readme_stars table_2021 --->
      - name: advent-readme-stars
        uses: k2bd/advent-readme-stars@v1
        with:
          userId: Averbea
          leaderboardId: 1717853
          year: 2022
          sessionCookie: ${{ secrets.AOC_SESSION }}
          tableMarker: <!--- advent_readme_stars table_2022 --->
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README stats
