name: Update README ⭐
on:
  push:
    branches: 
      - 'master'
      
  workflow_dispatch:
      
    
jobs:
  results-table:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: aoc-badges 2021
        uses: joblo2213/aoc-badges-action@v3
        with:
          userid: ${{ secrets.AOC_USERID }}
          session: ${{ secrets.AOC_SESSION }}
          year: 2021
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/2021%20total%20stars%20⭐-)[0-9]+(?=-yellow)'             
          daysCompletedRegex: '(?<=https:\/\/img\.shields\.io\/badge\/2021%20days%20completed-)[0-9]+(?=-red)'
          file: 'README.md'
      - name: aoc-badges 2022
        uses: joblo2213/aoc-badges-action@v3
        with:
          userid: ${{ secrets.AOC_USERID }}
          session: ${{ secrets.AOC_SESSION }}
          year: 2022
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/2022%20total%20stars%20⭐-)[0-9]+(?=-yellow)'             
          daysCompletedRegex: '(?<=https:\/\/img\.shields\.io\/badge\/2022%20days%20completed-)[0-9]+(?=-red)'
          file: 'README.md'
      - name: aoc-badges 2023
        uses: joblo2213/aoc-badges-action@v3
        with:
          userid: ${{ secrets.AOC_USERID }}
          session: ${{ secrets.AOC_SESSION }}
          year: 2023
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/2023%20total%20stars%20⭐-)[0-9]+(?=-yellow)'
          daysCompletedRegex: '(?<=https:\/\/img\.shields\.io\/badge\/2023%20days%20completed-)[0-9]+(?=-red)'
          file: 'README.md'
      

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README stats
          file_pattern: README.md
